### PR TITLE
Update logo and serve it via SSL

### PR DESCRIPTION
**Pull request by raul**

### CODE REVIEW

**Comment by raul** [comment]
Bump :) Who can help us to get this shipped?

**Comment by jonmountjoy** [comment]
Lo @dmcinnes - can you help?

**Comment by raul** [comment]
Looks like the @heroku/core-services folks own this repo - can we get help from one of you to review/merge this change please? It's not urgent but it's been sitting here for waaay too long :)  Thanks!

**Comment by spofdamon** [comment]
Sorry about that, I'll deploy it now. 👍

**Comment by spofdamon** [comment]
@raul For future reference, I'm guessing the reason nobody saw this because it was lacking the `reviewable` label. We filter our PR queues by `reviewable` to try to minimize the noise of in-progress PRs.

**Comment by raul** [comment]
Ah, I missed that somehow - will do from now on, thanks a ton @spofdamon !

**Pull request merged**
