### PR TITLE
Log app: 'telex' for each log line, please.

### PR DESCRIPTION
**Pull request by elight**

### CODE REVIEW

**Comment by kahlouie** [comment]
@apg @elight Is this in progress or reviewable? I can't tell.

**Comment by apg** [comment]
I have never seen this issue in my life. I'm not sure how I attached "in progress" to it...

**Comment by kahlouie** [comment]
noted @apg thanks.

**Comment by elight** [comment]
@apg I've seen this on every recent telex PR. Must be happening
automatically somehow.

**Comment by kahlouie** [comment]
closing this since it's included in #80

**Comment by elight** [comment]
:+1:

**Pull request closed without merging**
