### PR TITLE
Handle ranges in the platform api client

### LINKED ISSUE #47: Organization member lookup not taking into account paginated results
API returns HTTP 206 in these cases:
https://rollbar.com/Heroku-3/telex/items/100/

### PR DESCRIPTION
**Pull request by dmathieu**
Closes #47 

cc @dmcinnes @will @geemus

### CODE REVIEW

**Comment by dmcinnes** [comment]
LGTM, Thanks for the quick turnaround!

Maybe in the future it would be nice to return an iterator or something so we're not pulling all of the results into memory, though it looks like only the Heroku org it a problem with 214 members (we paginate by default when the result count is > 200):
https://dataclips.heroku.com/mfmfpcfptreprlhdrjfphqoaiesb-Fork-of-organizations-api-User-Count-Per-Org
I think we could handle 214 results :smile:

**Comment by geemus** [comment]
Could also specify `max=1000` to kick it further down the road.

**Comment by dmathieu** [comment]
I've updated this PR to fetch by batches of 1000 so we can make less requests.
I'm not sure we should just update the max when handling pagination is fairly trivial.

**Comment by geemus** [comment]
deployed

**Pull request merged**
