### PR TITLE
Add rollbar-blanket from gemgate and vendor gems

### PR DESCRIPTION
**Pull request by elight**
Adds rollbar-blanket.

Blocked until https://github.com/heroku/rollbar-blanket/pull/11 is merged and released.

### CODE REVIEW

**Comment by dmcinnes** [comment]
LGTM 👍

**Comment by rwz** [comment]
That's weird, why the gems are vendored as dirs and not `.gem`s?

**Comment by elight** [comment]
@rwz That ought to fix it.

**Comment by rwz** [comment]
Let's squash-merge it to not introduce 1MLOC commits to the history

**Comment by elight** [comment]
All prettified.

**Comment by dmcinnes** [comment]
Way better 👍

**Comment by rwz** [comment]
:+1:

**Comment by elight** [comment]
Still 86 files. Whoa...

**Comment by elight** [comment]
(better than 7.2k)

**Comment by elight** [comment]
@kahlouie good to go.

**Pull request merged**
