### PR TITLE
Exclude collaborators who have never logged in

### PR DESCRIPTION
**Pull request by mikehale**
This should help resolve: https://groups.google.com/a/heroku.com/d/msg/api/Bu9LfBMFLu0/6IzxHEEfBQAJ

### CODE REVIEW

**Comment by mikehale** [comment]
I was attempting to use last_login as a proxy for converted_on, but maybe that is not a good thing. It looks like that would include herokumanager.com emails which may not be what we want.

https://dataclips.heroku.com/vmyytzqvjlygcfrvalbjskvzldax-API-Users-who-have-never-logged-in-by-domain

/cc @dmcinnes

**Comment by dmcinnes** [comment]
@mikehale I think that should be fine, emails to herokumanager.com accounts will be forwarded to all org admins through premiumrush (though better controls around this behavior is a larger topic).

**Comment by mikehale** [comment]
I've updated the PR to lookup each user in api to see if they have a last_login timestamp before sending them notifications. This allows us to exclude users who have never logged in without changing anything on the api side. It does mean that we now have an N+1 query situation, but I'm hoping it won't cause performance issues for telex as this stuff should basically be happening in the background. Longer term we may want to introduce a users-filters endpoint for this use case similar to the one we already have for apps.

The other thing we will need to do after this ships is a one time scan of all users to remove any emails which have never logged in.

**Comment by gregburek** [comment]
💯

**Comment by dmcinnes** [comment]
Nice! LGTM 👍

**Pull request merged**
