### PR TITLE
Add rubocop and codeclimate configs

### PR DESCRIPTION
**Pull request by rwz**

### CODE REVIEW

**Comment by rwz** [comment]
The code I've tried to submit earlier was red on codeclimate because it wasn't using the 2.3 parser. I've copied their allegedly default config and only added 2.3 syntax support.

**Comment by rwz** [comment]
I'm going to reach out to Codeclimate regarding this. This is bullshit.

**Comment by rwz** [comment]
Ok, apparently codeclimate runs rubocop in 1.9 mode by default which effective ignores all the files using 2.0+ syntax. This PR switches codeclimate rubocop into 2.3 mode and since it can now parse all the files it previously couldn't, tons of new issues are discovered.

**Comment by rwz** [comment]
This is ready for review.

**Comment by elight** [comment]
Compliance failures.

**Comment by elight** [comment]
Erm, I mean Codeclimate failures

**Comment by rwz** [comment]
@elight yes, that's why I explicitly mentioned that in the comments above.

**Comment by dmcinnes** [comment]
Thanks!

**Comment by dmcinnes** [comment]
👍

**Pull request merged**
